name: First Workflow 
on: 
  workflow_dispatch:
    inputs:
      name: 
        required: true
        type: choice
        options:
          - env1
          - env2
          - env3
      
      id: 
        required: false
        type: string
        default: xxxxx-xxxxx-xxxx


jobs:
  builds:
    runs-on: ubuntu-latest

    steps: 
      - name: test
        run: | 
          exit 1

  outputs:
    runs-on: ubuntu-latest
    needs: builds
    if: ${{ needs.builds.result == 'failure' }}

    steps:
      - name: output
        run: |
          echo ${{ needs.builds.outputs }}
          echo ${{ needs.builds.result }}
