name: First Workflow 
on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: |
          echo "Simulating failure"
          # exit 1

  second_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: builds
    if: failure()

    steps:
      - name: Output Failure Information
        run: |
          echo "Builds job failed."
          echo "Result: ${{ needs.builds.result }}"
