name: First Workflow 
on: 
  workflow_dispatch:
    inputs:
      name: 
        required: true
        type: choice
        options:
          - yes
          - no
      
      id: 
        required: false
        type: string
        description: enter your id!


jobs:
  builds:
    runs-on: ubuntu-latest

    steps: 
      - name: test
        run: echo First workflow running successfully!
