name: Test Matrix

on: 
    workflow_dispatch: 
        inputs:
            names:
                type: string

jobs:
    prepare-matrix:
        runs-on: ubuntu-latest
        steps:
          - name: Prepare matrix array
            id: prepare-matrix
            run: |
              user="${{ github.event.inputs.names }}"
              userNames=$(echo $user | tr ',' '\n')
              echo "userNames=[$(echo $userNames | tr '\n' ',')]" >> $GITHUB_ENV
              echo "Matrix fruits array: $userNames"
            
    Job1:
        runs-on: ubuntu-latest
        needs: prepare-matrix
        strategy:
            max-parallel: 1
            matrix:
                test1: ["one", "two", "three"]
                test2: ["four", "five", "six"]
        
        steps:
            - name: test
              env:
                  testEnv: something
              run: echo ${{env.testEnv}}${{matrix.test1}}
            
            - name: dynamic matrix pointing
              run: |
                echo ${{ env.userNames }}
