name: Multiple Jobs
on: 
  push:
    branches: ['Master']

  workflow_dispatch: 
    inputs:
      name:
        description: name
        default: Alis
        required: true
        type: string
      

jobs:

  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2
        run: echo step 2 working


  Job2:
    needs: Job1 # used for running in sequence
    continue-on-error: true # used to run even if the existing job has failed.
    
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2
        run: echo step 2 working

  Job3:
    needs: Job1
    uses: ./.github/workflows/reuseable.yml
    with:
      name: "Test user"
    secrets: inherit
