name: Multiple Jobs
on: 
  push:
    branches: ['Master']

  workflow_dispatch: 
    inputs:
      name:
        description: name
        default: Alis
        required: true
        type: string
      

jobs:

  Job1:
    runs-on: ubuntu-latest
    outputs:
      sample-output: ${{ steps.step-2.outputs.name }}
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2
        id: step-2
        run: |
          echo "{name}={some_output}" >> $GITHUB_OUTPUT

  Job2:
    needs: Job1 # used for running in sequence
    continue-on-error: true # used to run even if the existing job has failed.
    
    runs-on: ubuntu-latest
    env:
      sample-output: ${{ needs.Job1.outputs.sample-output }}
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2          
        run: |
          echo "Output from Job 1: $sample-output"

  # Job3:
  #   needs: Job1
  #   uses: ./.github/workflows/reuseable.yml
  #   with:
  #     username: "Test user"
  #   secrets: inherit
  
  # Job4:
  #   needs: Job3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print output
  #       run: echo ${{ needs.Job3.outputs }}
