name: Multiple Jobs
on: push

jobs:

  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2
        run: echo step 2 working


  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo step 1 working
  
      - name: step 2
        run: echo step 2 working
