name: Add Repositories to Team

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
      org_name:
        description: 'Organization Name'
        required: true
      team_name:
        description: 'Team Name'
        required: true

jobs:
  add-repos-to-team:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Repositories to Team
      env:
        GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
        ORGANIZATION_NAME: ${{ github.event.inputs.org_name }}
        TEAM_NAME: ${{ github.event.inputs.team_name }}
      run: |
        for repo in $(curl -s -H "Authorization: token $GITHUB_TOKEN" -X GET "https://api.github.com/orgs/$ORGANIZATION_NAME/repos" | jq -r '.[].name'); do
          if [[ "$repo" == "${TEAM_NAME}"* ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" -X PUT "https://api.github.com/teams/$TEAM_NAME/repos/$ORGANIZATION_NAME/$repo"
            echo "Added $repo to the $TEAM_NAME team."
          fi
        done
