name: Reuseable
on: 
  workflow_call: 
    inputs:
      username: 
        description: your name
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ouptput
        run: echo "Running"
      - name: print input
        run: ${{inputs.username}}
