name: Reuseable
on: 
    workflow_call: 
        inputs:
          name: 
            type: string
            required: true
            description: your name

        outputs:
          myoutput:
            description: output
            value: Hello + ${{inputs.name}}

        secrets:
          someSecret:
            required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ouptput
        run: echo "Running"
