name: Telegram Notification

on: 
  workflow_dispatch

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "There has been a new push to the repository!"
