name: Pull Request Workflow

on: pull_request

# defaults:
#   run:
#     working-directory: action
#     shell: actor

env:
  EVENT_CONTEXT: ${{ toJson(github) }}

jobs:
  pr-check:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: action
    # if: ${{ vars.MY_VAR }} == 'MY_VALUE'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GitHub Predefined Variables
        if: ${{ always() }}
        run: |
          echo "GITHUB_ACTION: ${{ github.action }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_EVENT_PATH: ${{ github.event_path }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "GITHUB_SERVER_URL: ${{ github.server_url }}"
          echo "GITHUB_API_URL: ${{ github.api_url }}"
          echo "RUNNER_NAME: ${{ runner.name }}"
          echo "RUNNER_OS: ${{ runner.os }}"
          echo "RUNNER_TEMP: ${{ runner.temp }}"
          echo "RUNNER_TOOL_CACHE: ${{ runner.tool_cache }}"

      - name: Display Pull Request Information
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"
          echo "PR User: ${{ github.event.pull_request.user.login }}"
          echo "PR Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR Head Branch: ${{ github.event.pull_request.head.ref }}"

      - name: Display Event Details
        run: ${{ env.EVENT_CONTEXT }}
